import { expect, test } from "bun:test";
import * as fs from "node:fs/promises";
import * as os from "node:os";
import * as path from "node:path";
import { Settings, type CustomToolContext } from "@oh-my-pi/pi-coding-agent";
import type { Type } from "@oh-my-pi/pi-ai";
import { createWorkerTools } from "../worker-tools";

async function fixture(run: (root: string, outside: string) => Promise<void>) {
  const directory = await fs.mkdtemp(path.join(os.tmpdir(), "conduct-tools-"));
  const root = path.join(directory, "snapshot");
  const outside = path.join(directory, "outside.txt");
  await fs.mkdir(path.join(root, "src"), { recursive: true });
  await fs.writeFile(path.join(root, "src", "allowed.ts"), "export const name = 'before';\n");
  await fs.writeFile(path.join(root, "helper.ts"), "export const context = 'neighbor-secret';\n");
  await fs.writeFile(outside, "outside-secret");
  try {
    await run(root, outside);
  } finally {
    await fs.rm(directory, { recursive: true, force: true });
  }
}
async function tools(root: string, files = ["src/allowed.ts", "src/new.ts"], cwd = root) {
  const settings = Settings.isolated({ "edit.blockAutoGenerated": false });
  const definitions = await createWorkerTools({ root, cwd, files, settings });
  return async (name: string, args: unknown) => {
    const tool = definitions.find((tool) => tool.name === `conduct_${name}`)!;
    return tool.execute("policy-test", args, undefined, {} as CustomToolContext);
  };
}
function output(result: { content: { type: string; text?: string }[] }) {
  return result.content
    .filter((part) => part.type === "text")
    .map((part) => part.text)
    .join("\n");
}

test("workers read neighboring context but only edit and create exact allowed files", async () => {
  await fixture(async (root) => {
    const invoke = await tools(root);
    expect(output(await invoke("read", { path: "helper.ts" }))).toContain("neighbor-secret");
    expect(
      (
        await invoke("edit", {
          edits: [{ path: "src/allowed.ts", old_string: "'before'", new_string: "'after'" }],
        })
      ).isError,
    ).not.toBe(true);
    expect(await fs.readFile(path.join(root, "src/allowed.ts"), "utf8")).toBe(
      "export const name = 'after';\n",
    );
    expect(
      (await invoke("write", { path: "src/new.ts", content: "export const created = true;\n" }))
        .isError,
    ).not.toBe(true);
    expect(await fs.readFile(path.join(root, "src/new.ts"), "utf8")).toBe(
      "export const created = true;\n",
    );
    const blocked = await invoke("write", { path: "helper.ts", content: "changed" });
    expect(blocked.isError).toBe(true);
    expect(output(blocked)).toContain("fresh human-authorized scope");
    expect(await fs.readFile(path.join(root, "helper.ts"), "utf8")).toContain("neighbor-secret");
  });
});

test("nested working directories resolve inputs locally and allowlists from the snapshot root", async () => {
  await fixture(async (root) => {
    const invoke = await tools(root, ["src/allowed.ts"], path.join(root, "src"));
    expect(output(await invoke("read", { path: "../helper.ts" }))).toContain("neighbor-secret");
    expect((await invoke("write", { path: "allowed.ts", content: "nested" })).isError).not.toBe(
      true,
    );
    expect(await fs.readFile(path.join(root, "src/allowed.ts"), "utf8")).toBe("nested");
    expect((await invoke("write", { path: "../helper.ts", content: "changed" })).isError).toBe(
      true,
    );
  });
});

test("outside paths and native URI, selector, device, and multi-target transports are rejected", async () => {
  await fixture(async (root, outside) => {
    const invoke = await tools(root);
    const rejected = [
      outside,
      "../outside.txt",
      "https://example.com",
      "file:///etc/passwd",
      "local://escape",
      "artifact://escape",
      "ssh://host/etc/passwd",
      "xd://bash",
      "src/allowed.ts:raw",
      "src/allowed.ts%3Araw",
      "src/allowed.ts;../outside.txt",
      "archive.zip:src/allowed.ts",
      "database.db:users",
      "attachment://0",
      "src/allowed.ts\n../outside.txt",
    ];
    for (const target of rejected) {
      expect((await invoke("read", { path: target })).isError).toBe(true);
      expect((await invoke("write", { path: target, content: "overwrite" })).isError).toBe(true);
      expect(
        (
          await invoke("edit", {
            edits: [{ path: target, old_string: "before", new_string: "overwrite" }],
          })
        ).isError,
      ).toBe(true);
    }
    expect(await fs.readFile(outside, "utf8")).toBe("outside-secret");
    expect(await fs.readFile(path.join(root, "src/allowed.ts"), "utf8")).toContain("before");
  });
});

test("symlinks and Git metadata are neither traversed by discovery nor directly accessible", async () => {
  await fixture(async (root, outside) => {
    await fs.mkdir(path.join(root, ".git"));
    await fs.writeFile(path.join(root, ".git", "config"), "metadata-secret");
    await fs.symlink(outside, path.join(root, "linked.txt"));
    await fs.symlink(path.dirname(outside), path.join(root, "linked-dir"));
    await fs.link(outside, path.join(root, "hard-linked.txt"));
    const invoke = await tools(root);
    for (const target of [
      "linked.txt",
      "linked-dir/outside.txt",
      "hard-linked.txt",
      ".git/config",
      "src/../.git/config",
    ]) {
      expect((await invoke("read", { path: target })).isError).toBe(true);
      expect((await invoke("grep", { pattern: "secret", path: target })).isError).toBe(true);
    }
    const listing = output(await invoke("glob", { pattern: "**/*" }));
    expect(listing).toContain("helper.ts");
    expect(listing).not.toContain("linked");
    expect(listing).not.toContain(".git");
    const results = output(await invoke("grep", { pattern: "secret" }));
    expect(results).toContain("neighbor-secret");
    expect(results).not.toContain("outside-secret");
    expect(results).not.toContain("metadata-secret");
    for (const pattern of ["../**", "**/.git/**", "local://**", "**;../*"]) {
      expect((await invoke("glob", { pattern })).isError).toBe(true);
    }
  });
});

test("a symlink substituted after dispatch cannot redirect an allowed write or its ancestor", async () => {
  await fixture(async (root, outside) => {
    const invoke = await tools(root);
    await fs.unlink(path.join(root, "src/allowed.ts"));
    await fs.symlink(outside, path.join(root, "src/allowed.ts"));
    expect((await invoke("write", { path: "src/allowed.ts", content: "changed" })).isError).toBe(
      true,
    );
    await fs.unlink(path.join(root, "src/allowed.ts"));
    await fs.rmdir(path.join(root, "src"));
    await fs.symlink(path.dirname(outside), path.join(root, "src"));
    expect((await invoke("write", { path: "src/new.ts", content: "changed" })).isError).toBe(true);
    expect(await fs.readFile(outside, "utf8")).toBe("outside-secret");
    expect(await Bun.file(path.join(path.dirname(outside), "new.ts")).exists()).toBe(false);
  });
});

test("batch scope rejection and later native match failure leave earlier files untouched", async () => {
  await fixture(async (root) => {
    const invoke = await tools(root);
    const first = { path: "src/allowed.ts", old_string: "'before'", new_string: "'after'" };
    expect(
      (
        await invoke("edit", {
          edits: [first, { path: "helper.ts", old_string: "neighbor", new_string: "changed" }],
        })
      ).isError,
    ).toBe(true);
    expect(await fs.readFile(path.join(root, "src/allowed.ts"), "utf8")).toContain("before");
    await fs.writeFile(path.join(root, "src/new.ts"), "no matching needle");
    expect(
      (
        await invoke("edit", {
          edits: [
            first,
            { path: "src/new.ts", old_string: "missing literal", new_string: "changed" },
          ],
        })
      ).isError,
    ).toBe(true);
    expect(await fs.readFile(path.join(root, "src/allowed.ts"), "utf8")).toContain("before");
    expect(await fs.readFile(path.join(root, "src/new.ts"), "utf8")).toBe("no matching needle");
    expect((await invoke("edit", { edits: [first, first] })).isError).toBe(true);
  });
});

test("worker-supplied native capability knobs cannot introduce a second execution path", async () => {
  await fixture(async (root) => {
    const invoke = await tools(root);
    for (const [name, args] of [
      ["write", { path: "src/allowed.ts", content: "changed", tool: "bash" }],
      ["read", { path: "helper.ts", query: "execute code" }],
      ["grep", { pattern: "secret", path: ".", followSymlinks: true }],
      ["glob", { pattern: "**/*", cwd: "/" }],
      ["edit", { input: '<SM:EDIT path="helper.ts">' }],
      [
        "edit",
        {
          edits: [
            {
              path: "src/allowed.ts",
              old_string: "before",
              new_string: "changed",
              rename: "helper.ts",
            },
          ],
        },
      ],
    ] as const)
      expect((await invoke(name, args)).isError).toBe(true);
    expect(await fs.readFile(path.join(root, "src/allowed.ts"), "utf8")).toContain("before");
  });
});

test("nullable optional fields preserve directory, read, search and edit defaults", async () => {
  await fixture(async (root) => {
    const invoke = await tools(root);
    const directory = await invoke("read", { path: ".", startLine: null, endLine: null });
    expect(directory.isError).not.toBe(true);
    expect(output(directory)).toContain("helper.ts");
    expect(
      output(await invoke("read", { path: "helper.ts", startLine: null, endLine: null })),
    ).toContain("1: export const context");
    expect(output(await invoke("glob", { pattern: "**/*.ts", path: null, limit: null }))).toContain(
      "src/allowed.ts",
    );
    expect(
      output(
        await invoke("grep", {
          pattern: "neighbor-secret",
          path: null,
          ignoreCase: null,
          limit: null,
        }),
      ),
    ).toContain("neighbor-secret");
    expect(
      (
        await invoke("edit", {
          edits: [
            {
              path: "src/allowed.ts",
              old_string: "'before'",
              new_string: "'nullable'",
              replace_all: null,
            },
          ],
        })
      ).isError,
    ).not.toBe(true);
    expect(await fs.readFile(path.join(root, "src/allowed.ts"), "utf8")).toContain("'nullable'");
  });
});

test("non-UTF8 and NUL-containing edits fail before any batch member changes bytes", async () => {
  await fixture(async (root) => {
    const invoke = await tools(root);
    const invalid = Buffer.concat([Buffer.from("before"), Buffer.from([0xff, 0xfe])]);
    await fs.writeFile(path.join(root, "src/new.ts"), invalid);
    expect((await invoke("read", { path: "src/new.ts" })).isError).toBe(true);
    expect(output(await invoke("grep", { pattern: "before", path: "src/new.ts" }))).toBe(
      "No matches",
    );
    const result = await invoke("edit", {
      edits: [
        { path: "src/allowed.ts", old_string: "'before'", new_string: "'after'" },
        { path: "src/new.ts", old_string: "before", new_string: "after" },
      ],
    });
    expect(result.isError).toBe(true);
    expect(await fs.readFile(path.join(root, "src/new.ts"))).toEqual(invalid);
    expect(await fs.readFile(path.join(root, "src/allowed.ts"), "utf8")).toContain("'before'");
    const binary = Buffer.from("before\0retained");
    await fs.writeFile(path.join(root, "src/new.ts"), binary);
    expect(
      (
        await invoke("edit", {
          edits: [{ path: "src/new.ts", old_string: "before", new_string: "after" }],
        })
      ).isError,
    ).toBe(true);
    expect((await invoke("write", { path: "src/new.ts", content: "replacement\0" })).isError).toBe(
      true,
    );
    expect(await fs.readFile(path.join(root, "src/new.ts"))).toEqual(binary);
  });
});

test("published schemas reject malformed calls and runtime errors permit corrected retries", async () => {
  await fixture(async (root) => {
    const definitions = await createWorkerTools({
      root,
      cwd: root,
      files: ["src/allowed.ts", "src/new.ts"],
      settings: Settings.isolated({ "edit.blockAutoGenerated": false }),
    });
    const replacement = { path: "src/allowed.ts", old_string: "before", new_string: "after" };
    for (const [name, args] of [
      ["read", { path: "helper.ts", "i:": "<parameter=type>", content: "" }],
      ["read", { path: "helper.ts", offset: 1, limit: 20 }],
      ["write", { path: "src/new.ts", content: "", i: "Writing file" }],
      ["edit", {}],
      ["edit", { edits: '<SM:EDIT path="src/allowed.ts">' }],
      ["edit", { edits: ["src/allowed.ts"] }],
      ["edit", { edits: [{ path: "src/allowed.ts", original: "before", normalized: "after" }] }],
      ["edit", { edits: [] }],
      ["read", { path: "" }],
      ["read", { path: "helper.ts", startLine: 1.5 }],
      ["read", { path: "helper.ts", endLine: Number.MAX_SAFE_INTEGER + 1 }],
      ["glob", { pattern: "**/*", limit: 1001 }],
      ["grep", { pattern: "name", limit: 0 }],
      ["grep", { pattern: "name", path: "" }],
    ] as const) {
      const definition = definitions.find((entry) => entry.name === `conduct_${name}`)!;
      expect(() => (definition.parameters as Type).assert(args)).toThrow();
      const result = await definition.execute("malformed", args, undefined, {} as CustomToolContext);
      expect(result.isError).toBe(true);
      expect(result.details).toBeUndefined();
      expect(output(result)).toContain("JSON example:");
      expect(output(result)).not.toContain("fresh human-authorized scope");
    }
    const write = definitions.find((entry) => entry.name === "conduct_write")!;
    const valid = { path: "src/new.ts", content: "" };
    expect((write.parameters as Type).assert(valid)).toEqual(valid);
    const recovered = await write.execute("recovered", valid, undefined, {} as CustomToolContext);
    expect(recovered.isError).not.toBe(true);
    expect(recovered.details).toEqual({ changed: true });
    expect(await fs.readFile(path.join(root, "src/new.ts"), "utf8")).toBe("");
    const edit = definitions.find((entry) => entry.name === "conduct_edit")!;
    const recoveredEdit = await edit.execute(
      "recovered-edit",
      { edits: [replacement] },
      undefined,
      {} as CustomToolContext,
    );
    expect(recoveredEdit.isError).not.toBe(true);
    expect(recoveredEdit.details).toEqual({ changed: true });
    expect(await fs.readFile(path.join(root, "src/allowed.ts"), "utf8")).toBe(
      "export const name = 'after';\n",
    );
    expect((edit.parameters as Type).assert({
      edits: [{ ...replacement, new_string: "", replace_all: null }],
    })).toEqual({ edits: [{ ...replacement, new_string: "", replace_all: null }] });
    for (const [name, args] of [
      ["read", { path: "helper.ts", startLine: null, endLine: null }],
      ["glob", { pattern: "**/*", path: null, limit: null }],
      ["grep", { pattern: "", path: null, limit: null, ignoreCase: null }],
    ] as const) {
      const definition = definitions.find((entry) => entry.name === `conduct_${name}`)!;
      expect((definition.parameters as Type).assert(args)).toEqual(args);
    }
  });
});

test("writes distinguish UTF-8 no-ops, empty truncation and absent empty creation without rewriting", async () => {
  await fixture(async (root) => {
    const invoke = await tools(root);
    const target = path.join(root, "src/allowed.ts");
    const content = "\uFEFFé🙂\n";
    const first = await invoke("write", { path: "src/allowed.ts", content });
    expect(first.details).toEqual({ changed: true });
    expect(output(first)).toContain(`${Buffer.byteLength(content)} UTF-8 bytes`);
    const timestamp = new Date("2001-01-01T00:00:00Z");
    await fs.utimes(target, timestamp, timestamp);
    const before = await fs.stat(target, { bigint: true });
    const same = await invoke("write", { path: "src/allowed.ts", content });
    expect(same.details).toEqual({ changed: false });
    expect(output(same)).toContain("No change");
    expect((await fs.stat(target, { bigint: true })).mtimeNs).toBe(before.mtimeNs);
    expect(await fs.readFile(target)).toEqual(Buffer.from(content));

    const truncated = await invoke("write", { path: "src/allowed.ts", content: "" });
    expect(truncated.details).toEqual({ changed: true });
    expect(output(truncated)).toContain("0 UTF-8 bytes");
    expect(await fs.readFile(target)).toEqual(Buffer.alloc(0));
    await fs.utimes(target, timestamp, timestamp);
    const emptyBefore = await fs.stat(target, { bigint: true });
    const emptyAgain = await invoke("write", { path: "src/allowed.ts", content: "" });
    expect(emptyAgain.details).toEqual({ changed: false });
    expect(output(emptyAgain)).toContain("0 UTF-8 bytes");
    expect((await fs.stat(target, { bigint: true })).mtimeNs).toBe(emptyBefore.mtimeNs);
    const created = await invoke("write", { path: "src/new.ts", content: "" });
    expect(created.details).toEqual({ changed: true });
    expect(output(created)).toContain("0 UTF-8 bytes");
    expect(await fs.readFile(path.join(root, "src/new.ts"))).toEqual(Buffer.alloc(0));
  });
});

test("unchanged native edits preserve bytes and mixed failures remain atomic", async () => {
  await fixture(async (root) => {
    const invoke = await tools(root);
    const target = path.join(root, "src/allowed.ts");
    const other = path.join(root, "src/new.ts");
    await fs.writeFile(target, "\uFEFFbefore é\n");
    await fs.writeFile(other, "before\n");
    const timestamp = new Date("2001-01-01T00:00:00Z");
    await fs.utimes(target, timestamp, timestamp);
    const before = await fs.stat(target, { bigint: true });
    const noop = { path: "src/allowed.ts", old_string: "before", new_string: "before" };
    const unchanged = await invoke("edit", { edits: [noop] });
    expect(unchanged.isError).toBe(true);
    expect(unchanged.details).toBeUndefined();
    expect((await fs.stat(target, { bigint: true })).mtimeNs).toBe(before.mtimeNs);
    const mixed = await invoke("edit", {
      edits: [
        { path: "src/new.ts", old_string: "before", new_string: "" },
        noop,
      ],
    });
    expect(mixed.isError).toBe(true);
    expect(mixed.details).toBeUndefined();
    expect(await fs.readFile(other, "utf8")).toBe("before\n");
    expect(await fs.readFile(target)).toEqual(Buffer.from("\uFEFFbefore é\n"));
    expect((await fs.stat(target, { bigint: true })).mtimeNs).toBe(before.mtimeNs);
    const corrected = await invoke("edit", {
      edits: [
        { path: "src/allowed.ts", old_string: "before", new_string: "after" },
        { path: "src/new.ts", old_string: "before", new_string: "" },
      ],
    });
    expect(corrected.isError).not.toBe(true);
    expect(corrected.details).toEqual({ changed: true });
    expect(await fs.readFile(target)).toEqual(Buffer.from("\uFEFFafter é\n"));
    expect(await fs.readFile(other, "utf8")).toBe("\n");
  });
});

test("captured authority cannot be expanded by mutating the caller's allowlist", async () => {
  await fixture(async (root) => {
    const files = ["src/allowed.ts"];
    const invoke = await tools(root, files);
    files.push("helper.ts");
    expect((await invoke("write", { path: "helper.ts", content: "changed" })).isError).toBe(true);
    expect(await fs.readFile(path.join(root, "helper.ts"), "utf8")).toContain("neighbor-secret");
  });
});
