import type { Stats } from "node:fs";
import * as fs from "node:fs/promises";
import * as path from "node:path";
import { type, type TSchema } from "@oh-my-pi/pi-ai";
import { type CustomTool, type Settings } from "@oh-my-pi/pi-coding-agent";
import { EditSession, EditStore, editInspect, search } from "@oh-my-pi/pi-natives";

const freshScope =
  "Stop and request fresh human-authorized scope (requested files and reason); dispatch a fresh candidate after authorization.";
class AccessError extends Error {}
interface TextResult {
  content: { type: "text"; text: string }[];
  details?: { changed: boolean };
}
const text = (value: string): TextResult => ({ content: [{ type: "text", text: value }] });
const forbiddenPath = /[:%;\\*?[\]{}\p{Cc}]/u;
const containerFile =
  /\.(?:sqlite[23]?|db[23]?|zip|jar|war|ear|apk|whl|tar|tgz|gz|bz2|xz|zst|rar|7z|iso|cab|deb|rpm|cpio|ar|a|asar)$/i;

function record(value: unknown, keys: readonly string[]): Record<string, unknown> {
  if (!value || typeof value !== "object" || Array.isArray(value))
    throw new Error("Expected a JSON object");
  for (const key of Object.keys(value))
    if (!keys.includes(key)) throw new Error(`Unsupported parameter: ${key}`);
  return value as Record<string, unknown>;
}
function string(value: unknown, name: string): string {
  if (typeof value !== "string") throw new Error(`${name} must be a string`);
  return value;
}
function integer(value: unknown, fallback: number, maximum: number): number {
  if (value === undefined || value === null) return fallback;
  if (typeof value !== "number" || !Number.isSafeInteger(value) || value < 1 || value > maximum) {
    throw new Error(`Expected a positive integer no greater than ${maximum}`);
  }
  return value;
}
function boolean(value: unknown): boolean {
  if (value !== undefined && value !== null && typeof value !== "boolean")
    throw new Error("Expected a boolean");
  return value === true;
}
function decodeText(bytes: Uint8Array): string {
  const source = new TextDecoder("utf-8", { fatal: true, ignoreBOM: true }).decode(bytes);
  if (source.includes("\0")) throw new Error("NUL-containing binary text is unsupported");
  return source;
}
function within(root: string, target: string): boolean {
  const relative = path.relative(root, target);
  return (
    relative === "" ||
    (!path.isAbsolute(relative) && relative !== ".." && !relative.startsWith(`..${path.sep}`))
  );
}

/** Task-path enforcement, not an OS sandbox. No arbitrary worker code is executed. */
export async function createWorkerTools(input: {
  root: string;
  cwd: string;
  files: readonly string[];
  settings: Settings;
}): Promise<CustomTool[]> {
  const root = path.resolve(input.root);
  const cwd = path.resolve(input.cwd);
  // Capture only the setting the native matcher needs, never a live mutable authority object.
  const blockAutoGenerated = input.settings.get("edit.blockAutoGenerated");
  if (!within(root, cwd)) throw new Error("Worker cwd must be inside its snapshot root");
  // Check the root's own ancestors too: a symlink must not become an alternate snapshot root.
  async function inspect(target: string, absent: boolean): Promise<Stats | undefined> {
    const parsed = path.parse(target);
    let current = parsed.root;
    const components = target.slice(parsed.root.length).split(path.sep).filter(Boolean);
    for (let index = 0; index < components.length; index++) {
      current = path.join(current, components[index]!);
      let stat;
      try {
        stat = await fs.lstat(current);
      } catch (error) {
        if (absent && (error as NodeJS.ErrnoException).code === "ENOENT") return undefined;
        throw error;
      }
      if (stat.isSymbolicLink()) throw new AccessError(`Symlink access is forbidden: ${current}`);
      if (index !== components.length - 1 && !stat.isDirectory())
        throw new Error(`Non-directory ancestor: ${current}`);
      if (index === components.length - 1) {
        if (!stat.isFile() && !stat.isDirectory())
          throw new Error(`Only regular files and directories are accessible: ${current}`);
        if (stat.isFile() && stat.nlink > 1)
          throw new AccessError(`Hard-linked files are forbidden: ${current}`);
        return stat;
      }
    }
    throw new Error("Filesystem root is not a worker target");
  }
  function resolve(value: string, base = cwd): string {
    if (!value || value.trim() !== value || forbiddenPath.test(value) || value.startsWith("~")) {
      throw new Error(`Only plain filesystem paths are supported: ${JSON.stringify(value)}`);
    }
    if (value.split("/").some((part) => part.toLowerCase() === ".git"))
      throw new AccessError("Git metadata access is forbidden");
    const target = path.resolve(base, value);
    if (!within(root, target)) throw new AccessError(`Path is outside the snapshot: ${value}`);
    return target;
  }
  const allowed = new Set<string>();
  for (const file of input.files) {
    if (path.isAbsolute(file)) throw new Error("Allowed targets must be snapshot-root-relative");
    const target = resolve(file, root);
    if (path.relative(root, target) !== file || target === root)
      throw new Error(`Allowed target must be an exact normalized file: ${file}`);
    allowed.add(target);
  }
  async function writable(value: string): Promise<string> {
    const target = resolve(value);
    if (!allowed.has(target))
      throw new AccessError(`Mutation target is not in the exact file allowlist: ${value}`);
    if (containerFile.test(target)) throw new Error("Archive and database mutation is unsupported");
    const stat = await inspect(target, true);
    if (stat && !stat.isFile()) throw new Error(`Mutation target is not a regular file: ${value}`);
    return target;
  }
  const rootStat = await inspect(root, false);
  if (!rootStat?.isDirectory() || !(await inspect(cwd, false))?.isDirectory())
    throw new Error("Snapshot root and cwd must be directories");
  for (const target of allowed) await writable(target);

  async function enumerate(target: string): Promise<string[]> {
    const stat = await inspect(target, false);
    if (stat?.isFile()) return [target];
    const result: string[] = [];
    async function visit(directory: string): Promise<void> {
      const entries = (await fs.readdir(directory, { withFileTypes: true })).sort((a, b) =>
        a.name.localeCompare(b.name),
      );
      for (const entry of entries) {
        if (entry.name.toLowerCase() === ".git" || entry.isSymbolicLink()) continue;
        // Unrepresentable names are never handed to a transport-aware native tool.
        if (forbiddenPath.test(entry.name)) continue;
        const child = resolve(path.join(directory, entry.name));
        if (entry.isDirectory()) {
          await inspect(child, false);
          await visit(child);
        } else if (entry.isFile()) {
          const info = await fs.lstat(child);
          if (info.nlink === 1) result.push(child);
        }
      }
    }
    await visit(target);
    return result;
  }
  const examples: Record<string, string> = {
    conduct_read: '{"path":"src/allowed.ts","startLine":1,"endLine":100}',
    conduct_glob: '{"pattern":"**/*.ts","path":".","limit":200}',
    conduct_grep: '{"pattern":"name","path":".","ignoreCase":false,"limit":200}',
    conduct_edit: '{"edits":[{"path":"src/allowed.ts","old_string":"before","new_string":"after","replace_all":false}]}',
    conduct_write: '{"path":"src/allowed.ts","content":"replacement text\\n"}',
  };
  // Serialize worker calls, including reads, so their own mutations cannot race preflight.
  let pending: Promise<unknown> = Promise.resolve();
  function tool(
    name: string,
    description: string,
    parameters: TSchema,
    keys: string[],
    run: (args: Record<string, unknown>, signal?: AbortSignal) => Promise<TextResult>,
  ): CustomTool {
    return {
      name,
      label: name,
      description: `${description} JSON example: ${examples[name]}. Use only this tool's fields; no extra i, offset, selectors, XML or legacy schemas. Paths are relative to worker cwd; no URIs, selectors, symlinks or Git metadata. Access restrictions require fresh authorization; malformed arguments should be corrected and retried.`,
      loadMode: "essential",
      strict: true,
      parameters,
      approval: name === "conduct_write" || name === "conduct_edit" ? "write" : "read",
      async execute(_id, params, _update, _context, signal) {
        const execution = pending.then(async () => {
          try {
            signal?.throwIfAborted();
            return await run(record(params, keys), signal);
          } catch (error) {
            return {
              ...text(
                error instanceof AccessError
                  ? `Access blocked: ${error.message}. ${freshScope}`
                  : `Failed: ${error instanceof Error ? error.message : String(error)}. Correct the arguments or matching text and retry. JSON example: ${examples[name]}. No extra i, offset, selectors, XML or legacy schemas; access restrictions still apply.`,
              ),
              isError: true,
            };
          }
        });
        pending = execution;
        return execution;
      },
    };
  }
  const plainPath = type("string").atLeastLength(1);
  const positiveInteger = (maximum: number) =>
    type("number").atLeast(1).atMost(maximum).divisibleBy(1).or("null");
  const editEntry = type({
    path: plainPath,
    old_string: "string",
    new_string: "string",
    "replace_all?": "boolean | null",
  }).onDeepUndeclaredKey("reject");
  return [
    tool(
      "conduct_read",
      "Read plain UTF-8 text with optional inclusive line range, or list a directory's immediate safe entries. Null optional fields use defaults.",
      type({
        path: plainPath,
        "startLine?": positiveInteger(Number.MAX_SAFE_INTEGER),
        "endLine?": positiveInteger(Number.MAX_SAFE_INTEGER),
      }).onDeepUndeclaredKey("reject"),
      ["path", "startLine", "endLine"],
      async (args) => {
        const target = resolve(string(args.path, "path"));
        const stat = await inspect(target, false);
        if (stat?.isDirectory()) {
          if (args.startLine != null || args.endLine != null)
            throw new Error("Line ranges require a file");
          const entries = await fs.readdir(target, { withFileTypes: true });
          const names: string[] = [];
          for (const entry of entries) {
            if (
              entry.name.toLowerCase() === ".git" ||
              entry.isSymbolicLink() ||
              forbiddenPath.test(entry.name)
            )
              continue;
            if (entry.isFile() || entry.isDirectory()) {
              const info = await fs.lstat(path.join(target, entry.name));
              if (info.isDirectory() || info.nlink === 1)
                names.push(entry.name + (entry.isDirectory() ? "/" : ""));
            }
          }
          return text(names.sort().join("\n") || "(empty directory)");
        }
        const start = integer(args.startLine, 1, Number.MAX_SAFE_INTEGER);
        const end = integer(args.endLine, start + 299, Number.MAX_SAFE_INTEGER);
        if (end < start || end - start >= 2000)
          throw new Error("Read range must be ordered and at most 2000 lines");
        if (stat!.size > 4 * 1024 * 1024) throw new Error("Plain text reads are limited to 4 MiB");
        const source = decodeText(await fs.readFile(target));
        return text(
          source
            .split("\n")
            .slice(start - 1, end)
            .map((line, index) => `${start + index}: ${line}`)
            .join("\n"),
        );
      },
    ),
    tool(
      "conduct_glob",
      "Match a relative glob against safely enumerated snapshot files. Hidden files included; ignores are not consulted. Maximum 1000 results. Null optional fields use defaults.",
      type({
        pattern: type("string").atLeastLength(1),
        "path?": plainPath.or("null"),
        "limit?": positiveInteger(1000),
      }).onDeepUndeclaredKey("reject"),
      ["pattern", "path", "limit"],
      async (args) => {
        const pattern = string(args.pattern, "pattern");
        if (
          !pattern ||
          /[:%;\\\p{Cc}]/u.test(pattern) ||
          path.isAbsolute(pattern) ||
          pattern.startsWith("~") ||
          pattern.split("/").some((part) => part === ".." || part.toLowerCase() === ".git")
        )
          throw new Error(
            "Glob must be a relative filesystem pattern without traversal or transports",
          );
        const target = resolve(args.path == null ? "." : string(args.path, "path"));
        const matcher = new Bun.Glob(pattern);
        const limit = integer(args.limit, 200, 1000);
        const files = await enumerate(target);
        const base = (await inspect(target, false))?.isFile() ? path.dirname(target) : target;
        const matches = files
          .filter((file) => matcher.match(path.relative(base, file)))
          .slice(0, limit);
        return text(matches.map((file) => path.relative(cwd, file)).join("\n") || "No matches");
      },
    ),
    tool(
      "conduct_grep",
      "Search safely enumerated plain files with native regex matching. Hidden files included; ignores are not consulted. Maximum 1000 matches; files above 4 MiB, invalid UTF-8 and binary files skipped. Null optional fields use defaults.",
      type({
        pattern: "string",
        "path?": plainPath.or("null"),
        "ignoreCase?": "boolean | null",
        "limit?": positiveInteger(1000),
      }).onDeepUndeclaredKey("reject"),
      ["pattern", "path", "ignoreCase", "limit"],
      async (args, signal) => {
        const pattern = string(args.pattern, "pattern");
        const ignoreCase = boolean(args.ignoreCase);
        const limit = integer(args.limit, 200, 1000);
        const files = await enumerate(resolve(args.path == null ? "." : string(args.path, "path")));
        const matches: string[] = [];
        for (const file of files) {
          signal?.throwIfAborted();
          const stat = await inspect(file, false);
          if (stat!.size > 4 * 1024 * 1024) continue;
          const bytes = await fs.readFile(file);
          let source: string;
          try {
            source = decodeText(bytes);
          } catch {
            continue;
          }
          const found = search(source, { pattern, ignoreCase, maxCount: limit - matches.length });
          if (found.error) throw new Error(found.error);
          for (const match of found.matches)
            matches.push(`${path.relative(cwd, file)}: ${JSON.stringify(match)}`);
          if (matches.length >= limit) break;
        }
        return text(matches.join("\n") || "No matches");
      },
    ),
    tool(
      "conduct_edit",
      "Apply a nonempty batch of native exact string replacements. edits: [{path, old_string, new_string, replace_all?}]. Each file appears once. No fuzzy matching, freeform grammar, rename, delete, repair or fallback execution. Every target is preflighted and all replacements staged before writes.",
      type({ edits: editEntry.array().atLeastLength(1) }).onDeepUndeclaredKey("reject"),
      ["edits"],
      async (args, signal) => {
        if (!Array.isArray(args.edits) || args.edits.length === 0)
          throw new Error("edits must be a nonempty array");
        const seen = new Set<string>();
        const edits = [];
        const original = new Map<string, Buffer | undefined>();
        for (const raw of args.edits) {
          const edit = record(raw, ["path", "old_string", "new_string", "replace_all"]);
          const target = await writable(string(edit.path, "path"));
          if (seen.has(target)) throw new Error("Each batch target must appear exactly once");
          seen.add(target);
          const old_string = string(edit.old_string, "old_string");
          const new_string = string(edit.new_string, "new_string");
          if (old_string.includes("\0") || new_string.includes("\0"))
            throw new Error("NUL-containing edits are unsupported");
          try {
            const bytes = await fs.readFile(target);
            decodeText(bytes);
            original.set(target, bytes);
          } catch (error) {
            if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
            original.set(target, undefined);
          }
          edits.push({
            path: target,
            old_string,
            new_string,
            replace_all: boolean(edit.replace_all),
          });
        }
        const staged = new Map<string, Buffer>();
        const reports: string[] = [];
        for (const edit of edits) {
          const json = JSON.stringify(edit);
          const inspection = editInspect("replace", json);
          if (
            inspection.paths.length !== 1 ||
            inspection.paths[0] !== edit.path ||
            inspection.fileOps.length !== 0
          )
            throw new Error("Native edit target inspection was ambiguous");
          const session = new EditSession(new EditStore(), {
            cwd,
            mode: "replace",
            allowFuzzy: false,
            fuzzyThreshold: 1,
            enforceSeenLines: false,
            blockAutoGenerated,
            planActive: false,
            homeDir: root,
            rawInput: false,
          });
          try {
            session.setArgsJson(json);
            session.finish();
            const result = await session.apply({ lspFlush: false }, async (error, request) => {
              if (error) throw error;
              if (
                request.path !== edit.path ||
                request.moveTo ||
                !["update", "create"].includes(request.op) ||
                request.content === undefined
              )
                throw new Error("Unsupported native mutation request");
              await writable(request.path);
              const bytes = Buffer.from(request.content, "utf8");
              if (!original.get(request.path)?.equals(bytes)) staged.set(request.path, bytes);
              return { written: request.content };
            });
            if (result.isError) throw new Error(result.text);
            reports.push(result.text);
          } finally {
            session.close();
          }
        }
        signal?.throwIfAborted();
        // Repeat the whole batch preflight before the first actual mutation.
        for (const target of staged.keys()) await writable(target);
        for (const [target, content] of staged) {
          signal?.throwIfAborted();
          await fs.mkdir(path.dirname(target), { recursive: true });
          signal?.throwIfAborted();
          await fs.writeFile(target, content);
        }
        return {
          ...text(staged.size ? reports.join("\n") : "No change: staged edits leave all bytes unchanged."),
          details: { changed: staged.size > 0 },
        };
      },
    ),
    tool(
      "conduct_write",
      "Write plain UTF-8 content to one exact allowed regular-file or absent target. No device, archive, database, LSP or formatter routing.",
      type({ path: plainPath, content: "string" }).onDeepUndeclaredKey("reject"),
      ["path", "content"],
      async (args, signal) => {
        const target = await writable(string(args.path, "path"));
        const content = string(args.content, "content");
        if (content.includes("\0")) throw new Error("NUL-containing writes are unsupported");
        const bytes = Buffer.from(content, "utf8");
        let existing: Buffer | undefined;
        try {
          existing = await fs.readFile(target);
        } catch (error) {
          if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
        }
        const changed = !existing?.equals(bytes);
        if (changed) {
          await writable(target);
          signal?.throwIfAborted();
          await fs.mkdir(path.dirname(target), { recursive: true });
          signal?.throwIfAborted();
          await fs.writeFile(target, bytes);
        }
        return {
          ...text(`${changed ? "Wrote" : "No change:"} ${path.relative(cwd, target)} (${bytes.length} UTF-8 bytes)`),
          details: { changed },
        };
      },
    ),
  ];
}
